name: pymc3-dev-py38
channels:
- conda-forge
- defaults
dependencies:
- aesara>=2.1.0
- arviz>=0.11.2
- cachetools>=4.2.1
- cloudpickle
- fastprogress>=0.2.0
- h5py>=2.7
- libpython
- mkl-service
- m2w64-toolchain
- numba
- numpy>=1.15.0
- pandas>=0.24.0
- pip
- python=3.8
- python-graphviz
- scipy>1.4.1
- typing-extensions>=3.7.4