name: pymc3-run-py38
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ipython>=7.16  
  - pymc3=3.11.4
  - aesara=2.2.1
  - matplotlib=3.2.2  
  - pandas>=1.2.0
  - seaborn=0.11.2
  - numpy>=1.15.0
  - scipy=1.4.1
  - graphviz>=2.48.0
  - python-graphviz=0.16
  - pip=21.2.2
  - arviz>=0.11.2
  - libblas=*=*mkl
  - mkl-service
  - pre-commit>=2.8.0
  - watermark
  - jupyter-book=0.11.3
